### ISSUE TITLE
Incomplete instructions

### ISSUE THREAD

**Issue by nkoren** [andreivolt/meteor-cordova-crosswalk-demo#2]
Thank you for posting this, but I've been unable to get it to work. The instructions don't seem complete. I've copied the cordova-build-override folder into my project, but then what? Where do I put the downloaded crosswalk lib? What do I do with it? The instructions seem to indicate that it should just be downloaded and then not used, but that can't be right...

Really appreciate any help you can give with this. Getting Crosswalk going has been such a nightmare!

**Comment by andreivolt** [comment]
As I've said in my post, I rushed this because of demand, so sorry for the lackluster instructions... Anyhow, this _should_ be enough to get you started though. You can simply copy the `cordova-build-override` into your project, and tweak the `AndroidManifest.xml` to match your project. Really what you should probably do is copy it over from an earlier build, and tweak it to add the "wifi" perm, as Cordova with Crosswalk requires it.

So, ignore the instructions, those were just some quick notes!

**Comment by andreivolt** [comment]
Also, if you try and build the demo app, it _should_ work. I haven't tested it, but there's no reason it shouldn't. Let me know if you have trouble running it.
